<?php
// Bộ từ điển comment các cột trong bảng dữ liệu.
return [
    'sakin' => [
        "t_media_head_id" => '媒体ヘッダID',
        "m_lang_id" => '言語マスタID',
        "media_name" => '媒体名',
        "del_flg" => '削除フラグ',
        "add_user_id" => '登録者ＩＤ',
        "add_datetime" => '登録日時',
        "upd_user_id" => '更新者ＩＤ',
        "upd_datetime" => '更新日時',
        "t_ctg_head_id" => 'カテゴリヘッダID',
        "ctg_id" => 'カテゴリID',
        "disp_seq" => '表示順序',
        "data_id" => 'データID',
        "file_name" => 'ファイル名',
        "t_series_mei_id" => 'シリーズ明細ID',
        "t_series_ver_id" => 'シリーズ版ID',
        "t_series_lang_id" => 'シリーズ言語ID',
        "t_series_head_id" => 'シリーズヘッダID',
        "m_user_id" => 'ユーザーマスタID',
        "color_name" => '色名',
        "color" => '色',
        "image_flg" => '画像フラグ',
        "exec_kbn" => '実行区分',
        "t_ctg_section_id" => 'カテゴリ管理項目ID',
        "memo" => 'メモ',
        "template_id" => 'テンプレートID',
        "status" => 'ステータス',
        "m_brand_id" => 'ブランドID',
        "brand_code" => 'ブランドコード',
        "brand_edaban" => 'ブランド枝番',
        "brand_name" => 'ブランド名',
        "brand_logo" => 'ブランドロゴ',
        "maker_code" => 'メーカーコード',
        "m_brand_his_id" => 'ブランド履歴ID',
        "m_maker_id" => 'メーカーID',
        "maker_name" => 'メーカー名',
        "maker_logo" => 'メーカーロゴ',
        "maker_name_forsale" => 'メーカー名　販社向け',
        "index_notation_1" => 'メーカー名　索引用表記1',
        "index_notation_2" => 'メーカー名　索引用表記2',
        "yomigana_1" => 'よみがな1',
        "yomigana_2" => 'よみがな2',
        "series" => 'シリーズ',
        "item" => '項目',
        "cad" => 'Cad',
        "id" => 'ID',
        "series_id" => 'シリーズID',
        "series_version" => 'シリーズ版',
        "indd_file_path" => 'InDDファイルパス',
        "zip_file_path" => 'Zipファイルパス',
        "object_storage_flg" => 'オブジェクトストレージフラグ',
        "series_deleted" => '削除済シリーズ',
        "exist_zip_indd" => 'InDDのZipファイル存在',
        "exist_file_indd" => 'InDDファイル存在',
        "exist_folder_indd" => 'InDDフォルダー存在',
        "exist_folder_indd_link" => 'InDDのLinkフォルダー存在',
        "exist_icon_caution_ai" => 'Ai注意アイコン存在',
        "exist_icon_caution_l_ai" => 'L Ai注意アイコン存在',
        "c_output_section_def_id" => '出力項目定義ID',
        "group_section_key_def" => 'グループ項目キー定義',
        "group_section_name" => '項目名グループ',
        "section_key_def" => '項目キー定義',
        "section_name" => '項目名',
        "require_flg" => '必須フラグ',
        "sort_order_group" => 'ソート順グループ',
        "sort_order_one_sheet" => '1シートのソート順',
        "sort_order_by_ctg" => 'カテゴリでのソート順',
        "output_one_sheet" => '1シートの出力',
        "output_by_ctg" => 'カテゴリでの出力',
        "list_series_convert_id" => 'ID変換シリーズリスト',
        "m_excelfiles_history_id" => 'Excelファイル履歴ID',
        "m_icon_color_id" => 'アイコンの色ID',
        "code" => 'コード',
        "background" => '背景',
        "border_width" => 'ボーダ幅',
        "border_color" => 'ボーダ色',
        "icon_version" => 'アイコンバージョン',
        "filename" => 'ファイル名',
        "nikna_disp_flg" => "Nikna's表示フラグ",
        "m_maker_his_id" => 'メーカー履歴ID ',
        "m_media_template_history_id" => '媒体テンプレート履歴ID',
        "use_stop_flag" => '使用・停止のフラグ',
        "m_template_id" => 'テンプレートID',
        "upload_flg" => 'アップロードフラグ',
        "type_flg" => 'タイプフラグ',
        "m_menu_id" => 'メニューID',
        "menu_name" => 'メニュー名',
        "oya_m_menu_id" => '親メニューID',
        "link" => 'リンク',
        "privilege_1" => '特権1',
        "privilege_2" => '特権2',
        "privilege_3" => '特権3',
        "privilege_4" => '特権4',
        "privilege_5" => '特権5',
        "privilege_6" => '特権6',
        "privilege_7" => '特権7',
        "ak_use_flg" => 'あかがねの使用フラグ',
        "m_msg_trans_id" => '翻訳メッセージID',
        "msg_jpn" => '日本語メッセージ',
        "msg_eng" => '英語メッセージ',
        "msg_cn" => '簡体語メッセージ',
        "m_role_id" => 'ロールID',
        "role_name" => 'ロール名',
        "parent_m_section_id" => '親項目ID',
        "tab_index" => '索引タブ',
        "unit_flg" => '単位フラグ',
        "output_excel_gen_flg" => '出力Excel生成フラグ',
        "sort_order" => 'ソート順',
        "web_renkei_flg" => 'Web連携フラグ',
        "check_input" => '入力チェック',
        "m_section_attr_indd_id" => 'InDD項目属性ID',
        "convert_group" => '変換グループ',
        "attr_name" => '属性名',
        "src_section" => 'ソース項目',
        "src_data_column" => 'ソースデータコラム',
        "m_sort_inch_id" => 'ソートインチID',
        "m_template_cate_id" => 'テンプレートカテゴリID',
        "template_file_path" => 'テンプレートファイルのパス',
        "locale" => 'ロケール',
        "privilege" => '特権',
        "m_user_api_id" => 'ユーザーAPIのID',
        "api_key" => 'Apiキー',
        "api_memo" => 'Apiメモ',
        "m_zimmer_item_refer_id" => 'Zimmer項目参照ID',
        "pimlus_item" => 'Pimlus項目',
        "zimmer_item" => 'Zimmer項目',
        "m_zimmer_meas_refer_id" => 'Zimmer測定参照ID',
        "series_name" => 'シリーズ名',
        "meas_id" => '測定ID',
        "zimmer_meas_id" => 'Zimmer測定ID',
        "m_zimmer_tokuchou_id" => 'Zimmer特長ID',
        "features_name" => '特長名',
        "type_name" => 'タイプ名',
        "type_name_3" => 'タイプ名3',
        "ssh_excelfiles_import_history_id" => 'SSH_Excelファイル取込履歴ID',
        "file_id" => 'ファイルID',
        "t_add_section_xml_historty_id" => '項目追加XML履歴ID',
        "t_yoyaku_series_lang_id" => '予約シリーズ言語ID',
        "t_yoyaku_series_mei_id" => '予約シリーズ名ID',
        "yoyaku_status" => '予約現状',
        "mode" => 'モード',
        "yoyaku_flg" => '予約フラグ',
        "template_name" => 'テンプレート名',
        "m_media_type_id" => '媒体タイプID',
        "t_cate_temp_number_id" => 'カテゴリ暫定番号ID',
        "section_number" => '項目番号',
        "t_chatroom_head_id" => 'チャットルームのヘッドID',
        "chatroom_name" => 'チャットルーム名',
        "chatroom_master" => 'チャットルームマスタ',
        "group_type" => 'グループタイプ',
        "t_chatroom_message_id" => 'チャットルームメッセージID',
        "user_id" => 'ユーザーID',
        "message" => 'メッセージ',
        "message_time" => 'メッセージ時間',
        "message_group" => 'メッセージグループ',
        "t_chatroom_user_id" => 'チャットルームユーザーID',
        "t_chatroom_user_message_id" => 'チャットルームユーザーメッセージID',
        "read_flg" => '読むフラグ',
        "t_core_id" => '基幹ID',
        "large_product_type_code" => '大商品タイプコード',
        "medium_product_type_code" => '中商品タイプコード',
        "small_product_type_code" => '小商品タイプコード',
        "sort_code" => 'ソートコード',
        "product_code" => '商品コード',
        "abb_code" => '略コード',
        "set_product_flg" => '商品フラグ設定',
        "packing_unit" => 'パッキング単位',
        "external_product_name" => '外部商品名',
        "external_abb_name" => '外部Abb名',
        "wholesale_price" => '卸単価',
        "price_without_tax" => '定価（税抜き）',
        "logistics_center_stock_flg" => 'ロジスティクスセンター在庫フラグ',
        "auto_order_flg" => '自動ソートフラグ',
        "standard_purchase_price" => '標準購入価格',
        "discount_rate_rebate" => '引率のリベート',
        "profit_exclusion_discount_price" => '利益除外割引価格',
        "profit_exclusion_discount_rate" => '利益除外割引率',
        "stock_flg" => '在庫フラグ',
        "supplier_code" => '仕入先コード',
        "lower_limit_stock_quantity" => '下限在庫量',
        "ordering_unit" => '注文単位',
        "registration_date" => '登録日付',
        "registration_time" => '登録時間',
        "delete_date" => '削除日付',
        "update_date" => '更新日付',
        "update_time" => '更新時間',
        "catalog_registration_flg" => 'カタログ登録フラグ',
        "abb_code2" => '略コード２',
        "price_table_output_flg" => '価格表出力フラグ',
        "large_catalog" => '大カタログ',
        "product_type_name" => '商品タイプ名',
        "supplier_name" => '仕入先名',
        "unit" => '単位',
        "tax_rate_flg" => '税率区分',
        "sale_category" => '販売カテゴリ',
        "sale_purchase_price_class" => '販売購入価格クラス',
        "center_lower_limit_stock_flg" => 'センター下限在庫フラグ',
        "price_with_tax" => '税込み金額',
        "switching_date" => '切り替え日付',
        "out_of_product_flg" => '廃盤フラグ',
        "upload_datetime" => 'アップロード日時',
        "t_core_maker_id" => '基幹メーカーID',
        "t_core_supplier_id" => '基幹仕入先ID',
        "t_core_supplier_convert_id" => '基幹仕入先変換ID',
        "t_ctg_renkei_output_id" => 'カテゴリ連携出力ID',
        "t_renkei_output_head_id" => '連携出力ヘッドID',
        "owner_flg" => 'オーナーフラグ',
        "image_help" => 'ヘルプ画像',
        "parent_ctg_section_id" => '親カテゴリ項目ID',
        "exist_unit_flg" => '既存単位フラグ',
        "output_excel_db_flg" => '出力Excelデータベースフラグ',
        "section_group" => '項目グループ',
        "index_keyword" => '索引スキーワード',
        "index_yomigana" => '索引よみがな',
        "t_ctg_url_renkei_id" => 'カテゴリURL連携ID',
        "url_prefix" => 'URLプレフィックス',
        "db_name" => 'データベース名',
        "_2d3d" => '２D３D',
        "series_prefix" => 'シリーズプレフィックス',
        "t_download_template_history_id" => 'ダウンロードテンプレート履歴ID',
        "screen" => '画面',
        "t_execute_large_group_history_id" => '実行大グループ履歴ID',
        "mount_size_number" => 'マウントサイズ番号',
        "indd_filename" => 'InDDファイル名',
        "excel_org_filename" => 'Excelの元のファイル名',
        "excel_filename" => 'Excelファイル名',
        "t_execute_large_group_id" => '実行大グループID',
        "add_user_id_backup" => 'バックアップユーザーIDの追加',
        "add_datetime_backup" => 'バックアップ日時の追加',
        "upd_user_id_backup" => 'バックアップユーザーID更新',
        "upd_datetime_backup" => 'バックアップ日時更新',
        "colspan" => 'コルスパン',
        "rowspan" => '行スパン',
        "t_execute_large_group_excel_backup_id" => '実行大グループExcelバックアップID',
        "t_execute_large_group_backup_id" => '実行大グループバックアップID',
        "process_order" => 'プロセス並び順',
        "data_post" => 'データポスト',
        "t_his_share_section_data_id" => '項目データID共有履歴',
        "t_series_mei_id_share" => '共有シリーズ名ID',
        "t_series_mei_id_target" => '対象シリーズ名ID',
        "t_section_data_id" => '項目データID',
        "m_common_spec_id" => '共通スッペクID',
        "data_kbn" => 'データ区分',
        "text_data" => 'テキストデータ',
        "org_filename" => '元のファイル名',
        "org_header_filename" => '元のヘッダーファイル名',
        "header_filename" => 'ヘッダーファイル名',
        "title" => 'タイトル',
        "note" => 'ノート',
        "alt" => 'Alt',
        "link_url" => 'URLリンク',
        "target" => '対象',
        "table_type" => 'テープルタイプ',
        "table_page" => 'テープルページ',
        "mei_share" => 'Mei共有',
        "list_common_spec" => '共通スッペクの一覧',
        "data_share" => '共有データ',
        "process_note" => 'プロセスノート',
        "t_import_core_history_id" => '基幹取り込み履歴ID',
        "exec_user_id" => '実行ユーザーID',
        "exec_datetime" => '実行日時',
        "log_filename" => 'ログファイル名',
        "template_filename" => 'テンプレートファイル名',
        "success_result" => '成功結果',
        "warning_result" => '警告結果',
        "error_result" => 'エラー結果',
        "t_import_core_history_detail_id" => '基幹取込履歴詳細ID',
        "old_value" => '旧値',
        "new_value" => '新値',
        "new_import_datetime" => '新取込日時',
        "old_import_datetime" => '旧取込日時',
        "type_update" => '更新タイプ',
        "t_import_core_maker_diff_id" => '基幹メーカー取込差分ID',
        "t_import_core_supplier_diff_id" => '基幹仕入先取込差分ID',
        "customer_code" => 'お客様コード',
        "t_import_item_no_price_id" => '商品品番価格ID',
        "run_diff_indd_flag" => '差分組版実行フラグ',
        "only_price_en_flg" => '英語価格のみフラグ',
        "check_upd_excelheader" => 'Excelヘッダー更新確認',
        "check_gachanko" => 'がっちゃんこチェック',
        "t_import_item_no_price_history_id" => '商品品番価格取り込み履歴ID',
        "update_item_no_error_msg" => '商品品番更新エラーメッセージ',
        "run_diff_error_msg" => '差分組版実行のエラーメッセージ',
        "t_import_item_no_price_item_id" => '商品品番価格取り込み項目ID',
        "t_item_info_id" => '商品情報ID',
        "series_item_no" => 'シリーズ商品品番',
        "catalog_item_no" => 'カタログ商品品番',
        "item_item_no" => '商品商品品番',
        "i7_item_no" => 'i7商品品番',
        "cadenas_item_no" => 'Cadenas商品品番',
        "tanka" => '単価',
        "tani" => '単位',
        "irisu" => '入り数',
        "min_num_1" => '最小番号１',
        "max_num_1" => '最大番号１',
        "slide_price_1" => 'スライド価格１',
        "min_num_2" => '最小番号２',
        "max_num_2" => '最大番号２',
        "slide_price_2" => 'スライド価格２',
        "min_num_3" => '最小番号３',
        "max_num_3" => '最大番号３',
        "slide_price_3" => 'スライド価格３',
        "min_num_4" => '最小番号4',
        "max_num_4" => '最大番号4',
        "slide_price_4" => 'スライド価格4',
        "min_num_5" => '最小番号5',
        "max_num_5" => '最大番号5',
        "slide_price_5" => 'スライド価格5',
        "shitsuryo" => '質量',
        "shitsuryo_tani" => '質量単位',
        "input_date" => '入力日付',
        "cad_url" => 'CAD URL',
        "shitsuryo_hani" => '質量範囲',
        "item_sort" => '項目ソート',
        "catalog_sort" => 'カテゴリソート',
        "output_jpn" => '日本語出力',
        "output_eng" => '英語出力',
        "output_cn" => '簡体語出力',
        "output_catalog_no_jpn" => '日本語カタログNo . 出力',
        "output_catalog_no_eng" => '英語カタログNo . 出力',
        "output_catalog_no_cn" => '簡体語カタログNo . 出力',
        "t_item_info_price_id" => '商品情報価格ID',
        "t_item_info_price_bk_id" => '商品情報価格バックアップID',
        "add_user_id_bk" => 'バックアップユーザーIDの追加',
        "add_datetime_bk" => 'バックアップ日時追加',
        "upd_user_id_bk" => 'バックアップユーザーIDの更新',
        "upd_datetime_bk" => 'バックアップ日時の更新',
        "is_sort_inch_flg" => 'インチソートフラグ',
        "t_item_no_compare_id" => '商品品番比較ID',
        "item_no_diff_flg" => '商品品番差分フラグ',
        "output_jpn_exist" => '出力日本語存在',
        "output_eng_exist" => '出力英語存在',
        "output_cn_exist" => '出力簡体語存在',
        "item_no_rows" => '商品品番行',
        "item_no_db_rows" => '商品品番データベース行',
        "item_no_price_rows" => '商品品番価格行',
        "item_no_price_db_rows" => '商品品番価格データベース行',
        "t_itemno_price_upload_id" => '商品品番価格アップロードID',
        "t_itemno_price_upload_history_id" => '商品品番価格アップロード履歴ID',
        "ctg_color" => 'カテゴリ色',
        "media_status" => '媒体ステータス',
        "flg_dummy" => '未設定フラグ',
        "t_mei_product_id" => 'Mei_商品ID',
        "checked" => 'チェック済み',
        "t_mei_spec_id" => 'Mei_スペックID',
        "spec_name" => 'スペック名',
        "spec_name_disp" => 'スペック表示名',
        "sort" => 'ソート',
        "ctg_no_1" => 'カテゴリNo . １',
        "ctg_name_1" => 'カテゴリ名１',
        "ctg_no_2" => 'カテゴリNo . ２',
        "ctg_name_2" => 'カテゴリ名２',
        "ctg_no_3" => 'カテゴリNo . ３',
        "ctg_name_3" => 'カテゴリ名３',
        "series_id_xml" => 'シリーズID XML',
        "series_id_section" => 'シリーズID項目',
        "version" => 'バージョン',
        "series_no" => 'シリーズNo . ',
        "item_no" => '商品品番',
        "price" => '価格',
        "t_msg_trans_upload_id" => '翻訳メッセージアップロードID',
        "lang_kbn" => '言語区分',
        "excel_uploaded" => 'Excelアップロード済み',
        "t_multi_export_history_id" => '一括エクスポート履歴ID',
        "t_multi_import_history_id" => '一括インポート履歴ID',
        "product_success_result" => '商品成功結果',
        "product_warning_result" => '商品警告結果',
        "product_error_result" => '商品エラー結果',
        "file_success_result" => '成功結果ファイル',
        "file_warning_result" => '警告結果ファイル',
        "file_error_result" => 'エラー結果ファイル',
        "t_output_ctg_base_id" => 'Dに基づくカテゴリ出力',
        "ctg_name" => 'カテゴリ名',
        "oya_t_ctg_head_id" => '親カテゴリヘッドID',
        "date_change" => '変更日付',
        "msg_action" => 'メッセージアクション',
        "t_output_setting_spec_base_id" => 'IDに基づくスペック設定出力',
        "ctg_id_large" => '大カテゴリID',
        "ctg_name_large" => '大カテゴリ名',
        "ctg_id_medium" => '中カテゴリID',
        "ctg_name_medium" => '中カテゴリ名',
        "ctg_id_small" => '小カテゴリID',
        "ctg_name_small" => '小カテゴリ名',
        "section_kubun" => '項目区分',
        "section_type" => '項目タイプ',
        "flg_unit" => '単位フラグ',
        "section_check_input" => '入力確認項目',
        "spec_table_flg" => 'スペックテープルフラグ',
        "t_output_spec_value_base_id" => 'IDに基づくスペック値出力',
        "section_value" => '項目値',
        "section_unit" => '単位項目',
        "t_pdf_muti_download_history_id" => 'PDF一括ダウンロード履歴ID',
        "t_pdf_muti_upload_history_id" => 'PDF一括アップロード履歴ID',
        "t_product_id" => '商品ID',
        "katashiki" => '型式',
        "t_product_bk_id" => '商品バックアップID',
        "t_upload_template_history_id" => 'テンプレートアップロード履歴ID',
        "maker_product_code" => 'メーカー商品コード',
        "maker_product_name" => 'メーカー商品名',
        "t_register_nikna_history_id" => "Nikna's登録履歴ID",
        "uploaded_filename" => '更新済ファイル名',
        "total_series" => 'シリーズ合計',
        "count_new_series" => '新シリーズ数え',
        "count_existing_series" => '既存シリーズ数え',
        "count_product_code" => '商品コード数え',
        "total_file_excel" => 'Excelファイル合計',
        "count_file_excel_error" => 'エラーExcelファイル数え',
        "count_file_excel_success" => '成功Excelファイル数え',
        "t_register_nikna_history_detail_id" => "Nikna's登録履歴詳細ID",
        "syuyaku_series_name" => '集約シリーズ名',
        "syuyaku_flg" => '集約フラグ',
        "small_group_filename" => '小グループファイル名',
        "product_code_exists" => '既存の商品コード',
        "create_new_series_flg" => '新シリーズ作成ID',
        "creation_status" => 'ステータス作成',
        "at_excel_row" => 'Excelの行で',
        "t_renkei_head_id" => '連携ヘッドID',
        "head_name" => 'ヘッド名',
        "tate_yoko" => '縦横',
        "ext_type" => '拡張タイプ',
        "t_renkei_head_address_id" => '連携ヘッドアドレスID',
        "head_col" => 'ヘッドコラム',
        "head_row" => 'ヘッド行',
        "head_value" => 'ヘッド値',
        "t_renkei_head_address_his_id" => '連携ヘッドアドレス履歴ID',
        "ver" => 'バージョン',
        "t_renkei_head_value_id" => '連携ヘッド値ID',
        "section" => '項目',
        "value_type" => '値タイプ',
        "image_size" => '画像サイズ',
        "static_value" => '静的な値',
        "t_renkei_head_value_his_id" => '連携ヘッド値履歴ID',
        "output_name" => '出力名',
        "t_role_assign_id" => 'ロール割り当てID',
        "t_role_ctg_id" => 'ロールカテゴリID',
        "t_role_section_id" => 'ロール項目ID',
        "t_section_id" => '項目ID',
        "free_section_flg" => 'フリー項目フラグ',
        "pre" => 'プレフィックス',
        "suf" => 'サフィックス',
        "disp_section_name" => '項目表示名',
        "data_share_eng_flg" => '英語共有データフラグ',
        "data_share_cn_flg" => '簡体語共有データフラグ',
        "t_section_data_common_spec_lang_id" => '項目データ共通スペック言語ID',
        "m_common_spec_lang_id" => '共通スペック言語ID',
        "t_section_data_media_type_id" => '項目データ媒体タイプID',
        "media_type_no" => '媒体タイプNo . ',
        "t_section_data_share_id" => '項目データ共有ID',
        "share_lang_id" => '共有言語ID',
        "t_section_data_spec_lang_id" => '項目データスペック言語ID',
        "t_section_trans_id" => '項目翻訳ID',
        "m_section_id" => '項目ID',
        "lang_set_id" => '言語設定ID',
        "pm_request_user" => 'PM承認ユーザー',
        "other_flg" => '他のフラグ',
        "cad_url_kbn" => 'CAD URL区分',
        "section_edit" => '項目編集',
        "t_series_require_trans_id" => '翻訳必須シリーズID',
        "org_t_series_lang_id" => '元のシリーズの言語ID',
        "org_t_series_ver_id" => '元のシリーズ版ID',
        "org_t_series_mei_id" => '元のシリーズ名ID',
        "org_m_lang_id" => '元の言語ID',
        "dest_t_series_lang_id" => '宛先シリーズの言語ID',
        "dest_t_series_ver_id" => '宛先シリーズ版ID',
        "dest_t_series_mei_id" => '宛先シリーズ名ID',
        "dest_m_lang_id" => '宛先言語ID',
        "status_trans" => '翻訳ステータス',
        "check_section_flg" => '項目確認フラグ',
        "date_memo" => 'メモ日付',
        "t_series_mei_old_id" => '旧シリーズ名ID',
        "t_ser_ins_id" => 'シリーズ指示ID',
        "t_other_series_ver_id" => '他のシリーズ',
        "free_id" => 'フリーID',
        "data_option" => 'オプションデータ',
        "tmp_file_name" => '暫定ファイル名',
        "t_spec_translate_id" => 'スペック翻訳ID',
        "item_jpn" => '日本語項目',
        "item_eng" => '英語項目',
        "item_cn" => '簡体語項目',
        "t_spec_translate_his_id" => 'スペック翻訳履歴ID',
        "t_table_image_id" => 'テープル画像ID',
        "tag_name" => 'タグ名',
        "image_name" => '画像名',
        "image_tmp_file" => '暫定画像ファイル',
        "free_item_id" => 'フリー項目ID',
        "t_select_multi_data_id" => '複数データ選択ID',
        "t_typeset_multi_id" => 'タイプセット複数ID',
        "uid" => 'Uid',
        "data_type" => 'データタイプ',
        "media_id" => '媒体ID',
        "template_set_id" => 'テンプレートセットID',
        "lock_errmsg" => 'ロックエラーメッセージ',
        "exec_errmsg" => '実行エラーメッセージ',
        "lock_id" => 'ロックID',
        "old_id" => '旧ID',
        "old_status" => '旧ステータス',
        "multi_upload" => '一括アップロード',
        "t_upload_template_queue_id" => 'テンプレートキューIDアップロード',
        "fullpath" => 'フルパス',
        "tmp_upload_path" => '暫定アップロードパス',
        "folderunzip" => '解凍フォルダー',
        "folder_ctg_end" => '末端カテゴリのフォルダー',
        "statistics_upload_result" => '統計アップロード結果',
        "file_msg_error" => 'エラーメッセージファイル',
        "t_yoyaku_head_name" => '予約ヘッド名',
        "t_yoyaku_item_info_price_id" => '予約商品情報価格ID',
        "t_yoyaku_item_info_price_bk_id" => '予約商品情報価格バックアップID',
        "t_yoyaku_pdf_muti_download_history_id" => '予約PDF複数ダウンロード履歴ID',
        "result" => '結果',
        "folder" => 'フォルダー',
        "t_yoyaku_pdf_muti_upload_history_id" => '予約PDF複数アップロード履歴ID',
        "t_yoyaku_product_id" => '予約商品ID',
        "t_yoyaku_section_id" => '予約項目ID',
        "t_yoyaku_section_data_id" => '予約項目データID',
        "t_yoyaku_section_data_media_type_id" => '予約項目データ媒体タイプID',
        "t_yoyaku_section_data_spec_lang_id" => '予約項目データスペック言語ID',
        "t_yoyaku_table_image_id" => '予約テープル画像ID',
        "t_multi_data_id" => '複数のデータID',
        "t_zimmer_image_id" => 'Zimmer 画像ID',
        "exist_flg" => '既存フラグ',
        "t_zimmer_import_history_id" => 'Zimmer取込履歴ID',
        "mail_address" => 'メールアドレス',
        "t_zimmer_import_history_detail_id" => 'Zimmer取込履歴詳細ID',
        "org_file_generated" => '生成済元ファイル',
        "error_msg" => 'エラーメッセージ',
        "t_zimmer_meas_id" => 'Zimmer測定ID',
        "value" => '値',
        "article" => 'アーティクル',
        "t_zimmer_meas_item_id" => 'Zimmer測定項目ID',
        "column_no" => '列No . ',
        "meas_name" => '測定名',
        "table_id" => 'テープルID',
        "t_zimmer_selection_id" => 'Zimmer選択ID',
        "rail_manufacturer" => 'レールメーカー',
        "rail_type" => 'レールタイプ',
        "rail_size" => 'レールサイズ',
        "carriage_type" => 'キャリッジタイプ',
        "adapter_plate" => 'アダプタープレート',
        "masking_tape" => 'マスキングテープ',
        "t_req_id" => 't_req_id',
        "req_datetime" => '日時キューリクエスト',
        "corp_nm" => '協力名',
        "major_ver" => 'メジャーバージョン',
        "minor_ver" => 'マイナーバージョン',
        "template_path" => 'テンプレートパス',
        "xml_path" => 'Xmlパス',
        "proc_status" => 'プロセスステータス',
        "image_path" => '画像パス',
        "table_path" => 'テーブルパス',
        "indd_output_path" => 'InDD出力パス',
        "pdf_output_path" => 'PDF出力パス',
        "jpg_output_path" => 'JPG出力パス',
        "log_output_path" => 'ログ出力パス',
        "ver_no" => 'バージョン番号',
        "t_req_src_id" => 'ソースキューリクエストID',
        "old_flg" => '旧フラグ',
    ],
    'table_ignore' => [
        "t_yoyaku_bk_typeset_files",
        "t_yoyaku_comment",
        "t_yoyaku_ctg",
        "t_yoyaku_export_history",
        "t_yoyaku_head",
        "t_yoyaku_import_history",
        "t_yoyaku_item_info",
        "t_yoyaku_item_info_price",
        "t_yoyaku_item_info_price_bk",
        "t_yoyaku_pdf_muti_download_history",
        "t_yoyaku_pdf_muti_upload_history",
        "t_yoyaku_product",
        "t_yoyaku_section",
        "t_yoyaku_section_data",
        "t_yoyaku_section_data_media_type",
        "t_yoyaku_section_data_spec_lang",
        "t_yoyaku_ser_relation",
        "t_yoyaku_series_approval",
        "t_yoyaku_series_lang",
        "t_yoyaku_series_mei",
        "t_yoyaku_series_relation",
        "t_yoyaku_series_relation_info",
        "t_yoyaku_series_share",
        "t_yoyaku_series_ver",
        "t_yoyaku_table_image",
        "t_zimmer_image",
        "t_zimmer_import_history",
        "t_zimmer_import_history_detail",
        "t_zimmer_meas",
        "t_zimmer_meas_item",
        "t_zimmer_meas_item_old",
        "t_zimmer_meas_old",
        "t_zimmer_selection",
        "t_zimmer_selection_full",
        "t_zimmer_selection_old",
        "tmp_1",
        "tmp_category",
        "tmp_category_section",
        "tmp_check_series_id",
        "tmp_code_20220824",
        "tmp_itemno",
        "tmp_m_name",
        "tmp_product_20220808",
        "tmp_product_renkei",
        "tmp_product_title",
        "tmp_series_0315",
        "tmp_series_0427",
        "tmp_series_2_0302",
        "tmp_series_2_0316",
        "tmp_series_2_0317",
        "tmp_series_2_0330",
        "tmp_series_2_0421",
        "tmp_series_20220927",
        "tmp_series_product_0116",
        "v_t_req_queue_src",
        "t_ser_relation_lang_1",
        "t_section_data_20200423",
        "t_renkei_head",
        "t_renkei_head_address",
        "t_renkei_head_address_his",
        "t_renkei_head_value",
        "t_renkei_head_value_his",
        "t_renkei_output_head",
        "t_product_20200422",
        "t_import_history",
        "t_import_item_no_price",
        "t_import_item_no_price_history",
        "t_import_item_no_price_item",
        "t_item_info",
        "t_item_info_price",
        "t_item_info_price_bk",
        "t_item_no_compare",
        "t_iteminfo_sort",
        "t_iteminfo_sort_copy",
        "t_itemno_price_upload",
        "t_itemno_price_upload_history",
        "t_core_sknd_78",
        "t_core_supplier",
        "t_core_supplier_convert",
        "t_core_maker_0912",
        "t_core_maker_1013",
        "t_core_convert_sknd_78",
        "t_core_0612",
        "t_core_1123",
        "t_core_1202",
        "t_chatroom_head",
        "t_chatroom_message",
        "t_chatroom_user",
        "t_chatroom_user_message",
        "new_tmp_product_price",
        "ssh_excelfiles_import_history",
        "ssh_m_excelfiles",
        "ssh_m_excelfiles_data",
        "t_add_section_xml_historty",
        "m_zimmer_item_refer",
        "m_zimmer_meas_refer",
        "m_zimmer_tokuchou",
        "m_menu_20221007",
        "m_maker_0612",
        "m_maker_1123",
        "m_maker_1202",
        "m_excelfiles_history",
        "cad_url_en",
        "check_folder_links",
        "check_folder_links_y",
        "list_series_convert",
        "m_brand",
        "m_brand_his"  
    ],   
];